### ISSUE TITLE
jx-webhook-events pods are failing in multi-cluster setup

### ISSUE THREAD

**Issue by arkadiusz-konopka-collibra** [jenkins-x-plugins/jx-kh-check#61]
I have a multi-cluster JenkinsX setup on GKE, the installation was done according to the [multi-cluster example](https://jenkins-x.io/v3/admin/guides/multi-cluster/multi-cluster-example/) documentation.

I know that the part of this setup was to disable webhooks, but it seems that the kuberhealthy checks are still enabled and I'm not sure how to disable them permanently. And because of that, the jx-webhook-events pods are failing with the below error:

```
time="2022-04-05T08:59:18Z" level=info msg="Found instance namespace: jx"
time="2022-04-05T08:59:18Z" level=info msg="Kuberhealthy is located in the jx namespace."
starting jx-webhook-events health checks
FATAL: failed to list source repositories: failed to find local endpoints: failed to find endpoints hook in namespace jx: endpoints "hook" not found
```

I have tried to disable jx-webhook-events by adding the custom values.yaml to helmfiles/jx dir and attach it to jxgh/jx-kh-check chart in helmfile.yaml wit the below content:

```
jxWebhookEvents:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-webhook-events
  runInterval: 5m # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
jxWebhooks:
  enabled: false
  image:
    repository: ghcr.io/jenkins-x/jx-webhooks
  runInterval: 90s # The interval that Kuberhealthy will run your check on
  timeout: 2m # After this much time, Kuberhealthy will kill your check and consider it "failed"
```

The webhook ConfigMaps were removed from the config-root after PR merge, but it looks like the kuberhealthy deployment was not updated with this change, and the pods are still deploying and failing in jx namespace.

Also the jx health status -A is returning below errors:

```
NAME                          NAMESPACE                     STATUS                        ERROR MESSAGE
certmanager-tls               kuberhealthy                  OK                   
daemonset                     kuberhealthy                  OK                   
deployment                    kuberhealthy                  OK                   
dns-status-internal           kuberhealthy                  OK                   
jx-bot-token                  jx                            ERROR                         Check execution error: jx/jx-bot-token: failed to see pod running within timeout
jx-install                    jx-git-operator               OK                   
jx-pod-status                 kuberhealthy                  OK                   
jx-secrets                    kuberhealthy                  OK                   
jx-webhook                    jx                            OK                   
jx-webhook-events             jx                            ERROR                         Check execution error: jx/jx-webhook-events: timed out waiting for checker pod to report in
network-connection-check      kuberhealthy                  OK                   
pod-restarts                  kuberhealthy                  OK   
```
