### ISSUE TITLE
Error in template if jxSecrets.enabled=true and jxSecrets.cluster.enabled=false

### ISSUE THREAD

**Issue by guillermomolina** [jenkins-x-plugins/jx-kh-check#63]
Given:

```yaml
jxSecrets:
  enabled: true
  cluster:
    enabled: true 
```

Template charts/jx-kh-check/templates/jx-secrets-check.yaml renders incorrectly:

```yaml
---
apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: jx-secrets
  annotations:
    docs.jenkins-x.io: https://jenkins-x.io/v3/admin/troubleshooting/secrets/
spec:
  runInterval: <no value>
  timeout: <no value>
  podSpec:
    securityContext:
      runAsUser: 999
      fsGroup: 999
    containers:
      - env:
			  image: <no value>:<no value>
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
    serviceAccountName: jx-secrets-sa
```

The "- env:" line is missing the empty array, it should be: "- env: []" or be removed
